### ISSUE TITLE
Incorrect pidfile path in init

### ISSUE THREAD

**Issue by aj-jester** [lesaux/puppet-kibana4#12]
There is a trailing `/` in the [pidfile](https://github.com/lesaux/puppet-kibana4/blob/master/templates/kibana.init#L28) which is causing the pidfile to be written incorrectly.

Removing the trailing `/` should fix the issue. I tested this in Ubuntu 12.04 and it works.

**Comment by lesaux** [comment]
Thank you for this, I just fixed this. I will soon publish the git
master branch to puppet forge.

On 2015-07-22 12:55 PM, AJ wrote:

> There is a trailing |/| in the pidfile
> https://github.com/lesaux/puppet-kibana4/blob/master/templates/kibana.init#L28
> which is causing the pidfile to be written incorrectly.
> 
> Removing the trailing |/| should fix the issue. I tested this in
> Ubuntu 12.04 and it works.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/lesaux/puppet-kibana4/issues/12.

## 

##

**Comment by aj-jester** [comment]
thanks :smile:
