### ISSUE TITLE
Use official Elastic.co Kibana repos

### ISSUE THREAD

**Issue by madAndroid** [lesaux/puppet-kibana4#14]
It appears as though Elastic have added Kibana to their official repos; the puppet modules for the other Elastic products in the ELK line have all got parameters to facilitate installation from the official repos. I'd like to suggest that we add the same capability to this module.

**Comment by oloc** [comment]
I agree with you.

Why do you tag your PR https://github.com/lesaux/puppet-kibana4/pull/15 "WIP" (work in progress)? It seems to be good to me. What should be improve?

**Comment by madAndroid** [comment]
> Why do you tag your PR #15 "WIP" (work in progress)? It seems to be good to me. What should be improve?

It's not 100% tested atm, although it's mostly working.. I'd like to add systemd support, but that may be best left to another PR

**Comment by lesaux** [comment]
Hello, madAndroid's work as been merged in the latest module release. Feedback is welcome.
