### ISSUE TITLE
feature request: install kibana plugins

### ISSUE THREAD

**Issue by igalic** [lesaux/puppet-kibana4#25]
new versions of kibana can be extended with plugins such as [sense](https://www.elastic.co/guide/en/sense/current/installing.html)

we should provide a defined type to help install these plugins

**Comment by eperdeme** [comment]
I guess it should be possible to 'borrow' the code from https://github.com/elastic/puppet-elasticsearch/blob/master/manifests/plugin.pp

**Comment by ghost** [comment]
+1

**Comment by lesaux** [comment]
I will look into this shortly.

**Comment by lesaux** [comment]
I'll reference what files are used in the puppet elasticsearch plugin support.

plugin_dir function:
https://github.com/elastic/puppet-elasticsearch/blob/master/lib/puppet/parser/functions/plugin_dir.rb

provider:
https://github.com/elastic/puppet-elasticsearch/blob/master/lib/puppet/provider/elasticsearch_plugin/plugin.rb

type:
https://github.com/elastic/puppet-elasticsearch/blob/master/lib/puppet/type/elasticsearch_plugin.rb

and the plugin manifest:
https://github.com/elastic/puppet-elasticsearch/blob/master/manifests/plugin.pp

It seems a good amount of work will be necessary. I hope to have more time to work on it shortly.

**Comment by pythianali** [comment]
I have a workaround with exec for installing plugins until lesaux gets this implemented properly:

 exec { 'run_kibana_marvel_install':
    command => 'bin/kibana plugin --install elasticsearch/marvel/latest',
    path   => '/opt/kibana:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin',
    unless  => 'test -d /opt/kibana/installedPlugins/marvel',
    notify => Service['kibana'],
  }

Change marvel to whatever plugin you need and shape the command accordingly.  For the unless part to work, you need to know what directory the plugin installs to.

**Comment by MichaelAicher** [comment]
@pythianali Thanks for the workaround! :)
But of course it would be appreciated if it would be managed by the module. -> +1

**Comment by marcinbojko** [comment]
Any ideas how to implement exec via foreman ?

**Comment by pythianali** [comment]
I think the easiest way to do it would be to put it in a manifest as a profile and then import that in to foreman and assign it to the node you want.

**Comment by marcinbojko** [comment]
I was afraid of this ;)

**Comment by lesaux** [comment]
simple module support has been updated in the latest release.
Some limitations exist, such as updating plugins.

**Comment by lesaux** [comment]
I'll close this issue for now.
