### ISSUE TITLE
Permissions - extraction

### ISSUE THREAD

**Issue by eperdeme** [lesaux/puppet-kibana4#26]
Howdy,

I notice when you extract the ZIP you force the permissions to root:root.

Should the permissions not be kibanaUSER/kibanagroup ? I can send a pull request in, but wondering if I was missing a reason why the directory and files should not be owned by the kibana user ?

**Comment by lesaux** [comment]
Hi eperdeme, thanks for the comment. I put this because some people don't manage their kibana user and group in this module (another users manifest, ldap or whatever). But, we could definitely do something when manage_user=>true. A PR is welcome!

**Comment by f0xtek** [comment]
Hi lesaux,

Shouldn't the owner on the extracted directory be set to kibana_user & kibana_group anyway regardless of whether this module manages the user/group?

Even if the user/group is managed by another module/ldap etc, having ownership set to root on the kibana directory prevents the kibana_user from executing the kibana binary (the extracted bin/ folder has 700 permisisons)?

Thoughts?

**Comment by lesaux** [comment]
Hi landerson61,
this doesn't seem to be the case.

```
ls -l /opt/
total 4
drwxr-xr-x 7 root root 4096 Jun 29 18:07 kibana-4.1.1-linux-x64
```

```
ps aux|grep kibana
kibana4   6357  0.4  1.6 976276 64968 ?        Sl   15:31   0:00 /opt/kibana-4.1.1-linux-x64/bin/../node/bin/node /opt/kibana-4.1.1-linux-x64/bin/../src/bin/kibana.js
root      6399  0.0  0.0  11740   932 pts/0    R+   15:33   0:00 grep --color=auto kibana
```

I still agree with you that this is an issue and we should chown the extracted directories to the kibana4_user.
I will look into the archive modules to see if ownership of the extracted dir is supported.
Thanks!

**Comment by f0xtek** [comment]
Hi lesaux,

As far as I can see, there doesn't seem to be support for changing ownership of extracted directories in the archive moduels. However I have submitted a PR to fix this issue. Hope it is ok!

Thanks

**Comment by lesaux** [comment]
Thanks for the PR - merging now.
