### ISSUE TITLE
Code different in Puppet Forge module compared to Github

### ISSUE THREAD

**Issue by f0xtek** [lesaux/puppet-kibana4#33]
Hi,

This module's code in Github is different from that in the Puppet Forge module. If installing this module using the Puppet Module Tool (puppet module install), then the functionality that is in the Github code is not in the installed module.

This causes issues when using r10k on puppet server to download this module from the forge.

I have verified this by manually downloading the tar.gz file from Puppet Forge and comparing against the module's code here on GitHub.

**Comment by cFire** [comment]
I can confirm this. Puppetforge code is older than the github master. Puppetforge does not even fix the permissions on the install dir yet.
I'm having librarian-puppet pull from github for now.

**Comment by lesaux** [comment]
Hello, thanks for your interest in this module.
I'll work on a new release shortly.

**Comment by f0xtek** [comment]
Thanks! :)

**Comment by lesaux** [comment]
Module was updated on the forge. Let me know if you see any issues with the release.

**Comment by cFire** [comment]
Thanks, pulling it into testing today.

**Comment by lesaux** [comment]
I'll close this issue. From now on I'll try to release on a more regular basis.
