### ISSUE TITLE
pid file issues

### ISSUE THREAD

**Issue by eperdeme** [lesaux/puppet-kibana4#37]
Howdy,

Just tried out 1.0.4 and getting PID file issues;

[root@mon001 kibana-4.3.0-linux-x64]# /etc/init.d/kibana4 start
/etc/init.d/kibana4: line 47: $pidfile: ambiguous redirect
kibana4 started.

Looks like no pidfile= is defined in the init file. I'll take a butchers as to why.

**Comment by lesaux** [comment]
Hum, it should have defaulted to /var/run/kibana.pid. 
The pid file param is slightly more tricky as it can be part of the yml config, but it also has to be part of the init.
I was also trying to support either "pid_file" or "pid.file" depending on the kibana version.
I'll take a look today.

**Comment by lesaux** [comment]
I guess I need to create some tests for this.
I've tried to install kibana 4.3.0 from archive, either with either pid.file specified or not. In both case the kibana4 init file has the correct 'pidfile=/var/run/kibana.pid' line.

**Comment by lesaux** [comment]
Hi eperme, do you have any more feedback on this?

**Comment by eperdeme** [comment]
I changed the my config to specify the PID and that worked so have not
looked art why it was needed;

config => {

 'pid.file'                            => '/var/run/kibana.pid',
}

**Comment by alex-harvey-z3q** [comment]
Fyi it's not working for me either, but worked when I explicitly set pid.file in config.

**Comment by lesaux** [comment]
closing issue as it has been dealt with in #43
