### ISSUE TITLE
Error: Could not find command ''"

### ISSUE THREAD

**Issue by baboune** [lesaux/puppet-kibana4#6]
Using an external download url is broken:

<code>
Notice: /Stage[main]/Kibana4::Install/Archive[kibana-4.0.0-linux-x64]/Archive::Download[kibana-4.0.0-linux-x64.tar.gz]/Exec[download archive kibana-4.0.0-linux-x64.tar.gz and check sum]/returns: executed successfully
Error: Could not find command ''
Error: /Stage[main]/Kibana4::Install/Archive[kibana-4.0.0-linux-x64]/Archive::Extract[kibana-4.0.0-linux-x64]/Exec[kibana-4.0.0-linux-x64 unpack]/returns: change from notrun to 0 failed: Could not find command ''
Notice: /Stage[main]/Kibana4::Install/File[/opt/kibana4]: Dependency Exec[kibana-4.0.0-linux-x64 unpack] has failures: true
Warning: /Stage[main]/Kibana4::Install/File[/opt/kibana4]: Skipping because of failed dependencies
Notice: /Stage[main]/Kibana4::Config/File[/opt/kibana4/kibana-4.0.0-linux-x64/config/kibana.yml]: Dependency Exec[kibana-4.0.0-linux-x64 unpack] has failures: true
Warning: /Stage[main]/Kibana4::Config/File[/opt/kibana4/kibana-4.0.0-linux-x64/config/kibana.yml]: Skipping because of failed dependencies
Notice: /Stage[main]/Kibana4::Service/File[/etc/init.d/kibana4]: Dependency Exec[kibana-4.0.0-linux-x64 unpack] has failures: true
Warning: /Stage[main]/Kibana4::Service/File[/etc/init.d/kibana4]: Skipping because of failed dependencies
Notice: /Stage[main]/Kibana4::Service/Service[kibana4]: Dependency Exec[kibana-4.0.0-linux-x64 unpack] has failures: true
Warning: /Stage[main]/Kibana4::Service/Service[kibana4]: Skipping because of failed dependencies
Notice: Finished catalog run in 12.76 seconds
</code>

init.pp

<code>
node default {
  $url = 'http://download.elastic.co/kibana/kibana/kibana-4.0.2-linux-x64.tar.gz'
  package { 'wget':
    ensure => installed,
  } -> # and then  
  class { '::kibana4':
    package_provider      => 'archive',
    package_download_url  => $url,
    install_dir           => '/opt/kibana4',
    kibana4_user          => 'kibana4',
    kibana4_group         => 'kibana4',
    kibana4_gid           => 200,
    kibana4_uid           => 200,
    elasticsearch_url     => 'http://10.10.10.10:9200',
  }
}
</code>

Dependencies pulled: 
==> server: /etc/puppet/modules
==> server: └─┬ lesaux-kibana4 (v0.0.9)
==> server:   └── camptocamp-archive (v0.6.2)

**Comment by baboune** [comment]
It is a problem with camptocamp archive see https://github.com/camptocamp/puppet-archive/issues/50
Use camptocamp archive 0.5.3

**Comment by lesaux** [comment]
Thanks for the update, I was about to take a look.

Sent from my iPhone

> On May 15, 2015, at 9:48 AM, baboune notifications@github.com wrote:
> 
> It is a problem with camptocamp archive see camptocamp/puppet-archive#50
> Use camptocamp archive 0.5.3
> 
> —
> Reply to this email directly or view it on GitHub.

## 

##

**Comment by lesaux** [comment]
Closing as the archive module has been fixed. Ultimately I would like to get rid of this dependency.
